spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: GATEWAY-SERVICE
server:
  port: 8889
eureka:
  instance:
      prefer-ip-address: true
      instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://jimmy:jimmy@localhost:8001/eureka/
#--------------------Zuul-----------------------
zuul:
  routes:
    member:
      path: /member/**
      serviceId: CONSUME-SERVICE
      sensitiveHeaders: "*"
    auth:
      path: /auth/**
      serviceId: RIGHT-SERVICE
      sensitiveHeaders: "*"
  retryable: false
  ignored-services: PRODUCER-SERVICE,QUARTZ-SERVICE
  ribbon:
    eager-load:
      enabled: true
  host:
    connect-timeout-millis: 3000
    socket-timeout-millis: 3000
  add-proxy-headers: true


#---------------------OAuth2---------------------
security:
  oauth2:
    client:
      access-token-uri: http://localhost:${server.port}/auth/oauth/token
      user-authorization-uri: http://localhost:${server.port}/auth/oauth/authorize
      client-id: web
    resource:
      user-info-uri:  http://localhost:${server.port}/auth/api/member
      prefer-token-info: false
ribbon:
  ReadTimeout: 3000
  ConnectTimeout: 3000
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 2
  eureka:
    enabled: true
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 3500